export const SET_USER = 'SET_USER';
export const SET_PKEY = 'SET_PKEY';
export const ADD_USER_PENDING = 'ADD_USER_START';
export const ADDED_USER = 'ADDED_USER';

export const SET_EMP_OFFERS = 'SET_EMP_OFFERS';
export const SET_CAREER_PROFILE = 'SET_CAREER_PROFILE';

export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const SET_ORG_OFFERS = 'SET_ORG_OFFERS';
export const SET_PROFESSIONALS = 'SET_PROFESSIONALS';